import assert from 'node:assert/strict'
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import probe from '../geatsc-plugin-batched-probe.mjs'
const three = new URL('./', import.meta.resolve('three/src/constants.js'))
const { BoxGeometry } = await import(new URL('geometries/BoxGeometry.js', three))
const { MeshBasicMaterial } = await import(new URL('materials/MeshBasicMaterial.js', three))
const { Matrix4 } = await import(new URL('math/Matrix4.js', three))
const { Vector4 } = await import(new URL('math/Vector4.js', three))
const { PerspectiveCamera } = await import(new URL('cameras/PerspectiveCamera.js', three))
const { ArrayCamera } = await import(new URL('cameras/ArrayCamera.js', three))
const { BufferGeometry } = await import(new URL('core/BufferGeometry.js', three))
const { BufferAttribute } = await import(new URL('core/BufferAttribute.js', three))
const { InterleavedBuffer } = await import(new URL('core/InterleavedBuffer.js', three))
const { InterleavedBufferAttribute } = await import(new URL('core/InterleavedBufferAttribute.js', three))
const { BatchedMesh: UpstreamBatchedMesh } = await import(new URL('objects/BatchedMesh.js', three))
const url = new URL('objects/BatchedMesh.js', three).href
const fileName = fileURLToPath(url)
const transformed = probe.configure().hostShims.transformSource({ fileName, text: fs.readFileSync(fileName, 'utf8') })
// Execute the experimental transformation's actual class against Three's
// dependencies. This is a behavior check, not native compiler certification.
const executable = transformed.replace(/from (['"])(\.\.?\/[^'"]+)\1/g,
  (_, quote, specifier) => `from ${quote}${new URL(specifier, url).href}${quote}`)
const { BatchedMesh } = await import(`data:text/javascript;base64,${Buffer.from(executable).toString('base64')}`)
const material = new MeshBasicMaterial()
const batch = new BatchedMesh(4, 128, 256, material)
const geometry = batch.addGeometry(new BoxGeometry())
const first = batch.addInstance(geometry)
const second = batch.addInstance(geometry)
const matrix = new Matrix4().makeTranslation(1, 2, 3)
batch.setMatrixAt(first, matrix)
assert.deepEqual(batch.getMatrixAt(first, new Matrix4()).elements, matrix.elements)
assert.deepEqual(batch.getColorAt(first, new Vector4()).toArray(), [1, 1, 1, 1])
batch.setColorAt(first, new Vector4(0.25, 0.5, 0.75, 0.5))
assert.deepEqual(batch.getColorAt(first, new Vector4()).toArray(), [0.25, 0.5, 0.75, 0.5])
batch.setVisibleAt(second, false)
assert.equal(batch.getVisibleAt(second), false)
const camera = new PerspectiveCamera(60, 1, 0.1, 100)
camera.position.z = 10
camera.updateMatrixWorld()
batch.updateMatrixWorld()
batch.onBeforeRender({}, {}, camera, batch.geometry, material)
assert.equal(batch._multiDrawCount, 1, 'main render excludes hidden instances')
batch.setVisibleAt(second, true)
batch.onBeforeShadow({}, batch, camera, camera, batch.geometry, material)
assert.equal(batch._multiDrawCount, 2, 'shadow render rebuilds visible instance list')
let customSortCalls = 0
batch.setCustomSort(function (list, sortCamera) {
  assert.equal(this, batch)
  assert.equal(sortCamera, camera)
  assert.equal(list.length, 2)
  list.reverse()
  customSortCalls++
})
batch.onBeforeRender({}, {}, camera, batch.geometry, material)
assert.equal(customSortCalls, 1, 'custom sorting preserves the batch receiver and camera')
batch.setCustomSort(null)
const arrayCamera = new ArrayCamera([camera])
arrayCamera.updateMatrixWorld()
batch.onBeforeRender({}, {}, arrayCamera, batch.geometry, material)
assert.equal(batch._multiDrawCount, 2, 'array-camera initialization selects its concrete frustum')
arrayCamera.cameras.length = 0
batch.onBeforeRender({}, {}, arrayCamera, batch.geometry, material)
assert.equal(batch._multiDrawCount, 0, 'empty array camera must not reuse stale frustums')
batch.onBeforeRender({}, {}, camera, batch.geometry, material)
assert.equal(batch._multiDrawCount, 2, 'ordinary camera rendering survives an array-camera pass')
batch.setInstanceCount(8)
assert.deepEqual(batch.getMatrixAt(first, new Matrix4()).elements, matrix.elements)
assert.deepEqual(batch.getColorAt(first, new Vector4()).toArray(), [0.25, 0.5, 0.75, 0.5])
const clone = batch.clone()
assert.deepEqual(clone.getMatrixAt(first, new Matrix4()).elements, matrix.elements)
assert.deepEqual(clone.getColorAt(first, new Vector4()).toArray(), [0.25, 0.5, 0.75, 0.5])
clone.setColorAt(first, new Vector4(1, 0, 0, 1))
assert.deepEqual(batch.getColorAt(first, new Vector4()).toArray(), [0.25, 0.5, 0.75, 0.5])
clone.setMatrixAt(first, new Matrix4().makeTranslation(4, 5, 6))
assert.deepEqual(batch.getMatrixAt(first, new Matrix4()).elements, matrix.elements)
assert.notEqual(clone._indirectTexture.source, batch._indirectTexture.source)
assert.notEqual(clone._indirectTexture.image.data, batch._indirectTexture.image.data)
const uncolored = new BatchedMesh(4, 128, 256, material)
const uncoloredGeometry = uncolored.addGeometry(new BoxGeometry())
const uncoloredInstance = uncolored.addInstance(uncoloredGeometry)
clone.copy(uncolored)
assert.deepEqual(clone.getColorAt(uncoloredInstance, new Vector4()).toArray(), [1, 1, 1, 1])
uncolored.dispose()
batch.deleteInstance(second)
assert.throws(() => batch.getMatrixAt(second, new Matrix4()), /[Ii]nstance/)
assert.equal(batch.addInstance(geometry), second, 'recycle the lowest available numeric instance ID')
batch.dispose()
clone.dispose()
material.dispose()

// Compare the adapter against upstream across native storage layouts, including
// normalized conversion and interleaved sources. These exercise the actual
// geometry copy/allocation methods rather than extracted replacement strings.
const kinds = [Int8Array, Uint8Array, Uint8ClampedArray, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array]
for (const Kind of kinds) {
  const normalized = Kind !== Uint8ClampedArray && Kind !== Float64Array
  const geometry = new BufferGeometry()
  const backing = new Kind([99, 99, 99, 1, 2, 3, 4, 5, 6])
  geometry.setAttribute('position', new BufferAttribute(backing.subarray(3), 3, normalized))
  const upstream = new UpstreamBatchedMesh(2, 8)
  const native = new BatchedMesh(2, 8)
  const expectedId = upstream.addGeometry(geometry)
  const actualId = native.addGeometry(geometry)
  assert.equal(actualId, expectedId)
  const compare = () => {
    const expected = upstream.geometry.getAttribute('position')
    const actual = native.geometry.getAttribute('position')
    assert.equal(actual.array.constructor, Kind)
    assert.equal(actual.normalized, expected.normalized)
    assert.deepEqual(actual.array, expected.array)
  }
  compare()
  const replacement = new BufferGeometry()
  replacement.setAttribute('position', new InterleavedBufferAttribute(new InterleavedBuffer(new Float32Array([99, 0.1, 0.2, 0.3, 99, 0.4, 0.5, 0.6]), 4), 3, 1, normalized))
  upstream.setGeometryAt(expectedId, replacement)
  native.setGeometryAt(actualId, replacement)
  compare()
  const converted = new BufferGeometry()
  converted.setAttribute('position', new BufferAttribute(new Uint16Array([10, 20, 30, 40, 50, 60]), 3, normalized))
  upstream.setGeometryAt(expectedId, converted)
  native.setGeometryAt(actualId, converted)
  compare()
  upstream.deleteGeometry(expectedId)
  native.deleteGeometry(actualId)
  assert.equal(native.addGeometry(geometry), upstream.addGeometry(geometry), 'recycle geometry IDs')
  compare()
  upstream.dispose()
  native.dispose()
  geometry.dispose()
  replacement.dispose()
  converted.dispose()
}
console.log('Experimental BatchedMesh preserves geometry, transforms, colors, visibility, render/shadow callbacks, resize, independent clone and deleted-instance checks')
